### PR TITLE
changed the style of the button in View.js

### LINKED ISSUE #53: Change 'Create Spreadsheet' button's style
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
Change `Create Spreadsheet` button's bootstrap class and add a fa icon to it.

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

In the following line:
https://github.com/publiclab/simple-data-grapher/blob/ecaf7eddc52cafb49310b069ef0bc056a2dabbb2/src/View.js#L519

Change **this**:

`<button type="button" class="btn btn-primary" id=' + this.createSpreadsheetButtonId + '> Create Spreadsheet</button>`

**TO**

`<button type="button" class="btn btn-success" id=' + this.createSpreadsheetButtonId + '> Create Spreadsheet <i class="fa fa-plus" aria-hidden="true"></i></button>`

(This is being done to change the styling of the button)
- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by SergeyTkachenko-Cj**
Fixes #53 

Thanks!

### CODE REVIEW

**Comment by SergeyTkachenko-Cj** [comment]
Mind to leave a review?

**Comment by IshaGupta18** [comment]
Greate work here @SergeyTkachenko-Cj ! Could you please provide a screenshot of what the button looks like now? Thanks a lot!

**Comment by SergeyTkachenko-Cj** [comment]
@IshaGupta18 Here is a screenshot of a new button 
Screenshot 2019-06-22 at 10 51 31

**Comment by IshaGupta18** [comment]
This looks great! Thanks a lot for your work here @SergeyTkachenko-Cj ! We would love your help on more issues!

**Pull request merged**
