### PR TITLE
Adding ESlint

### PR DESCRIPTION
**Pull request by IshaGupta18**
I have added eslint to the project. However, I think it needs to be configured a little more to fix the linting errors automatically. But for now, this works! 
@jywarren @namangupta01 @rexagod

### CODE REVIEW

**Comment by IshaGupta18** [comment]
@rexagod @jywarren what do you think of this one? I actually disabled some of the rules, but that's not a very good idea, I'll enable them is you think this is alright?

**Comment by rexagod** [comment]
Enable as many of them as you can work with, even if it's a bit uncomfortable and needs some refactoring. This will should ensure good code quality of this lib in the long run.

**Comment by IshaGupta18** [comment]
Yes, when I looked at the changes I made, I couldn't find the disabled
rules, if there were any. They are mostly at the top of the marked file in
comments right?

**Comment by rexagod** [comment]
Could be. Could be inside the `.eslintrc` too.

**Comment by IshaGupta18** [comment]
Yes, I checked, wasn't there. So this might be good to merge?

**Comment by rexagod** [comment]
Just to confirm, you guys never really linted the code, did you?

**Comment by rexagod** [comment]
Because I cannot see any eslint ignore rules as of now in any of the files.

**Comment by IshaGupta18** [comment]
Yes, I tried it locally I think, but never really linted it, as far as I
remember. You're right, there are no rules there.

**Comment by rexagod** [comment]
Maybe we should wait for @namangupta01's review here, or do you believe we should proceed with the merge?

**Comment by IshaGupta18** [comment]
I think there's not much to discuss in this one so we can proceed with the
merge. What do you think? Maybe we should wait for @jywarren 's approval?

**Comment by IshaGupta18** [comment]
Thanks a lot! :D

**Pull request merged**
