### PR TITLE
Stage 2 - UI Design

### PR DESCRIPTION
**Pull request by IshaGupta18**
This is the second stage of UI design. Here are a couple of screenshots and gifs:

image
image

stage2-2019-08-15_10 07 00

@jywarren @gauravano @sagarpreet-chadha @namangupta01 @Souravirus @ebarry please review and let me know if its good to go!

### CODE REVIEW

**Comment by ebarry** [comment]
WOW - looking great! the location of the "Plot Graph" button might be confusing because of its placement in the centered column where other buttons/setting are changing the type of graph. "Plot Graph" should somehow be clear as what to press after you've made all your other choices.

**Comment by IshaGupta18** [comment]
Thanks a lot! Yeah, I think you're right, maybe I can take it up in a follow up PR? If that's okay, we can merge this one, since it already has a lot in it!

**Comment by jywarren** [comment]
This is looking good! What kind of input would be useful to get from people? Would you like to use https://Lookback.io to do some user testing? 

One thing I noted was that sometimes it's not clear how buttons and things are grouped, and i wonder if you could use more light grey boxes (like GitHub uses) to group buttons and labels into panels/cards. What do you think? This may also help make clear the "direction of flow" i.e. what you're supposed to do /first/ or /second/ or /last/.

**Comment by jywarren** [comment]
Which is to say, we can refine this a bit, but it's basically good to go -- what I wonder is whether a more in-depth UI flow feedback project may be useful to you to see how people use the interface, what confuses them, etc etc.

**Comment by jywarren** [comment]
If you agree, we can merge and open a new issue to plan out UI process?

**Comment by IshaGupta18** [comment]
Yes, I completely agree with you. We can definitely take user opinion and then shape the next stage accordingly. Yes I think we should merge this one, and open a new planning issue to develop the UI! Thanks a lot!

**Comment by jywarren** [comment]
ok sounds great!

**Comment by jywarren** [comment]
Actually i also think it's worthwhile using a real sensor data CSV. This can really help you to refine the UI -- think about people not just who have some random CSV, but who downloaded a timeseries of sensor data - like temperature, or something. Maybe taking data from one of these posts? https://publiclab.org/tag/data-logging

Think of the steps people will go through, like a) take the SD card out and plug it in, b) drag the CSV file onto the screen, c) try to understand the change in temperature over time. How can we make that flow simple and intuitive?

**Comment by IshaGupta18** [comment]
I think that would be a good idea, to actually go through the process. Let's try it out, and put it in the planning follow-up issue.

**Pull request merged**
