### PR TITLE
Added new footer

### LINKED ISSUE #106: Add a footer to the page
Note:- **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Describe the idea or (feature)

We need to add a footer to the main page and provide some general information on it.

### Reference 

We can take a reference from this: https://beta.sequencer.publiclab.org/

reference
Thank You 😊

### PR DESCRIPTION
**Pull request by genesis331**
Fixes #106 

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` or the user who published the issue for help, in a comment below

SC1 (2)

### CODE REVIEW

**Comment by Ryan10145** [comment]
When running the program in localhost using `npm run dev_start`, I don't see the changes. You probably have to change index.html as well in order for the changes to be shown there. Additionally, when I went to the examples/index.html file that you did modify, the buttons didn't do anything. Please fix this! Other than that, the formatting looks good!

image
(What I see when I run using `npm run dev_start`)

**Comment by IshaGupta18** [comment]
Yes! You have to make the changes in View.js, in the string that renders the view!

**Comment by genesis331** [comment]
Thanks! @Ryan10145 and @IshaGupta18. I've made some changes here.

**Comment by debck** [comment]
@genesis331 Great Work. LGTM 👍 

@IshaGupta18  Have a look and kindly merge it if everything looks good

**Comment by genesis331** [comment]
Thanks for approving and merging!

**Pull request merged**
