### PR TITLE
Redesign Add Graph Button

### LINKED ISSUE #69: Redesign Add Graph Button
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
The current `Add Graph` button is a simple bootstrap primary button.
### 📋Solution

`<button type="button" class="btn btn-primary" id=' + this.addGraphButtonId + '> Add Graph</button>`

Change the above line in 

https://github.com/publiclab/simple-data-grapher/blob/fa222a480c402d15d260f70cb42c23694577e603/src/View.js#L347

By adding some styling, probably a `fa fa-icon` or some other color!

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by VarsPhilos**
Fixes #69
Added fa-chart-bar icon and changed style to match other buttons.

Did I do this pull request anywhere near correct?

### CODE REVIEW

**Comment by IshaGupta18** [comment]
I am so sorry to have missed it, could you please provide a screenshot of the new design?

**Comment by VarsPhilos** [comment]
Thank you for the opportunity!

IMG_3554

**Comment by IshaGupta18** [comment]
This looks good! Could you change the color of this button though?

**Comment by VarsPhilos** [comment]
It was blue originally, do you want it reverted back to that or do you have another color in mind?

**Comment by IshaGupta18** [comment]
Some other color? Maybe you could try out a couple?

**Comment by IMRC21** [comment]
In my opinion, a gradient would look really nice.
Btn_1
`background-image: linear-gradient( 359.8deg,  rgba(56,104,178,1) 7.3%, rgba(31,67,122,1) 84.8% );`

Btn_2
`background-image: linear-gradient( 90.6deg,  rgba(26,109,85,1) -0.1%, rgba(49,227,125,1) 105.9% );`

Btn_3
`background-image: linear-gradient( 90.6deg,  rgba(77,34,109,1) -1%, rgba(90,142,253,1) 153.1% );`

**Comment by IshaGupta18** [comment]
This looks good! Maybe you can try out the first one, along with the fa-icon given by @VarsPhilos ? Thanks a lot!

**Pull request closed without merging**
