### PR TITLE
[DO NOT MERGE] Testing issues

### PR DESCRIPTION
**Pull request by IshaGupta18**
@rexagod here you go! KIndly let me know what might be the problem here

### CODE REVIEW

**Comment by rexagod** [comment]
This was resolved, closing now.

/cc @IshaGupta18 @namangupta01 @jywarren 

```sh
npm run test

> publiclab-grapher@0.0.1 test /mnt/c/Users/Rexagod/Desktop/simple-data-grapher
> ./node_modules/mocha/bin/mocha --require @babel/register --require @babel/polyfill --require jsdom-global/register spec/js/



  Sample Test
[Function: sampleTest]
    ✓ Should return Mocha Testing


  1 passing (45ms)
```

**Comment by IshaGupta18** [comment]
@rexagod thanks a ton for your help here. Should I pull in these changes or copy them locally? Also, it would be great if you could tell me what exactly was going wrong here, which you fixed?

**Comment by rexagod** [comment]
> @rexagod thanks a ton for your help here. Should I pull in these changes or copy them locally? Also, it would be great if you could tell me what exactly was going wrong here, which you fixed?

This was clarified in the chatroom. Also, @IshaGupta18, any reason for reopening this?

**Comment by IshaGupta18** [comment]
I just reopened it to check something out, I am closing it right away.
Thanks again for your help!

**Comment by IshaGupta18** [comment]
Definitely, thanks again!

**Pull request closed without merging**
