### PR TITLE
Implementing basic parsing and header functions

### LINKED ISSUE #3: Parsing and getting Header names
This is for parsing the uploaded CSV and getting the header names by detecting columns

### PR DESCRIPTION
**Pull request by IshaGupta18**
Fixes #3 
Here's the working of the parsing function and getting header names:
@jywarren @namangupta01

parsing

### CODE REVIEW

**Comment by namangupta01** [comment]
Looking into your code, can you please add some small comments? It would be easy for me to understand your code?

**Comment by IshaGupta18** [comment]
Done!

**Comment by namangupta01** [comment]
I am making a basic project set up so that we have a good project structure. Will push in sometimes. Please update your this pr after that.

**Comment by jywarren** [comment]
awesome, folks!

**Comment by namangupta01** [comment]
I just saw that we are using main branch, I think master is a good convention. What do you say @jywarren, @IshaGupta18 ?

**Comment by IshaGupta18** [comment]
Good with either!

**Comment by namangupta01** [comment]
Isha, I have added dependencies into the package.json. You just have to do `npm install` to get the package in the node modules and you can use the library. It will be good to use it from there instead of adding the script in the head of html file. What do you say?

Sorry for asking so many changes -- I just want that we both follow as much as good practice we can so that we can learn more about the practices.

**Comment by namangupta01** [comment]
And if you are having some doubt regarding it? Do let me know.

**Comment by IshaGupta18** [comment]
No problem at all, we should follow the best practices! I'll get back to you after pulling in the changes!

**Comment by namangupta01** [comment]
I was looking at the https://github.com/publiclab/PublicLab.Editor/tree/master/src. There is some good example of how we can write code and we can follow some practices from there also.

**Comment by IshaGupta18** [comment]
And so what should we do about this PR? What do you think should be the required changes, or is it good to go?

**Comment by namangupta01** [comment]
You can make changes in this pr.

**Comment by IshaGupta18** [comment]
Just the removal of script files right?

**Comment by namangupta01** [comment]
You have imported `csv` parser script into the html file i.e `	<script src="https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.6.3/papaparse.min.js"></script>
` But it should not be there. It should be node_modules --that I have already done but you have to import it where you want to use it in the js code, not in the html code.

**Comment by IshaGupta18** [comment]
Can you explain the changes a little more?

**Comment by namangupta01** [comment]
Yes, for now, the removing of the scripts would work for us. But if you want, you can look into the best ways of dividing different functionality and integrating them into one area then you can have a look here https://github.com/publiclab/PublicLab.Editor/tree/master/src. It won't matter now for us because the project is just getting started but as the project grows there will be a lot of complexity. Just take your time researching it.

**Comment by IshaGupta18** [comment]
Yes, I understand a bit, however, unlike the Editor, we should keep our scripts a little divided, instead of making a single script file of 20,000+ lines.

**Comment by IshaGupta18** [comment]
However, the new script files which you have published will have to be included in the HTML file only right, something like here   https://github.com/publiclab/PublicLab.Editor/blob/master/examples/index.html 
Also, could we set up something similar for the bootstrap dependencies, like you did for the others? This sounds good! Lets get these changes on the road!

**Comment by IshaGupta18** [comment]
What do you say?

**Comment by jywarren** [comment]
Hi! Just in case it's useful, this is a little old, but helps for an
overview!

https://scotch.io/tutorials/a-simple-guide-to-getting-started-with-grunt

**Comment by IshaGupta18** [comment]
I am not sure why or how, but without a few of the script tags, I am getting some errors in the console

image

What I would suggest is we merge this PR with the script tags since they are functional, and then we can work on the dependencies for a little longer while and make sure they work correctly so that in the meanwhile the code remains functional and we can improve on the installation part. What do you think?

**Comment by jywarren** [comment]
Sure, as long as there's a good project plan and checklist, it's OK to
merge imperfect stuff early on and remember to fix later.

Re: the script tags, one issue may be that in a remote server, they don't
load as instantly as they do locally. So, you may need to wrap your
index.html code in a block that runs only after the whole page has loaded,
like this:

// we make a one-off function:
(function() {
  // put your code in here
})() // this then executes it but only after the page loads

**Comment by IshaGupta18** [comment]
Yes agreed!

**Comment by namangupta01** [comment]
Now we have set up the npm task runner instead of grunt you can change the dependency from the html file to the js file. HTML file should only contain one script.

**Comment by IshaGupta18** [comment]
Okay, could you please explain what exactly you did here? How do we install
the dependencies on our system and what all has to be removed from the
HTML file and added to the JS file? Thank you!

**Pull request closed without merging**
