### PR TITLE
Project Setup 

### LINKED ISSUE #6: Public Lab Grapher Project Setup
Public Lab Grapher Project Setup for easily installing the different dependencies and structuring the code files and tests.

### PR DESCRIPTION
**Pull request by namangupta01**
Project setup for the structuring of the project and easy installation of the dependencies.
Closes #6

### CODE REVIEW

**Comment by namangupta01** [comment]
@jywarren, Good to merge?

**Comment by jywarren** [comment]
Hi! What does @IshaGupta18 think? Thanks!

**Comment by IshaGupta18** [comment]
Oh this looks very good. So elegant!

**Comment by jywarren** [comment]
Maybe we start w v0.0.1? Otherwise good to merge!!!

**Comment by namangupta01** [comment]
Ya sure! Changing that.

**Comment by namangupta01** [comment]
Changed. Merging it.
Thanks

**Pull request merged**
