### PR TITLE
Plotting Graphs using Chart.js

### LINKED ISSUE #19: Graph Plotting
#18 is the PR which shows the working of graph plotting using chart.js.
@namangupta01 @jywarren please give your review!

### PR DESCRIPTION
**Pull request by IshaGupta18**
Here is the basic implementation of graph plotting!
fixes #19 
@namangupta01 @jywarren what do you think?
graph

### CODE REVIEW

**Comment by namangupta01** [comment]
This looks awesome!! Very well done. I just have one minor doubt, while selecting y-axis there should be some checking if that column can be selected because y-axis can only be number? or am I missing something?

**Comment by namangupta01** [comment]
I think this is dependent on #15 ?

**Comment by IshaGupta18** [comment]
Thanks a lot! And yes you are right, I did think about that, but I skipped
that just for now. But that is very important. Would you like to handle
that one?

**Comment by IshaGupta18** [comment]
Yes, it covers that up as well, merging this will close #15 I believe

**Comment by namangupta01** [comment]
How is the graph when we select a column with not all number values? For example column 1 in the above gif. Can you share the gif how it will look?

**Comment by namangupta01** [comment]
And also how it will look in multiple columns(column without numbers) on the y-axis. I think if it looks fine we can go with it. Can you share the gif?

**Comment by IshaGupta18** [comment]
With a non-numeric column, it would be empty, as expected:
image

**Comment by IshaGupta18** [comment]
With a mix of numeric and non-numeric, this is what it looks like:
image

**Comment by IshaGupta18** [comment]
Obviously, we will have to do some handling, but this is the basic functioning.

**Comment by namangupta01** [comment]
Also, I think we can have a separate button for update graph, rather than updating using csv upload button after the graph like Update Graph.

**Comment by namangupta01** [comment]
I think what you can do is that while processing and adding header you can check if that column is having not all numbers or not and then depending on that you put the checkbox? What do you say? It will solve our problem. Right?

**Comment by IshaGupta18** [comment]
Yes yes, that was just for a demo! Actually this is not how the page will look like. In the deisgn I have made, there are 3 tabs, 1 for upload, 2nd for column selection, 3rd for chart(s) display and export and other options

**Comment by namangupta01** [comment]
Oh Okay, so are you doing that checking in this pr. I think it won't take much time doing this. But it is up to you.

**Comment by IshaGupta18** [comment]
> I think what you can do is that while processing and adding header you can check if that column is having not all numbers or not and then depending on that you put the checkbox? What do you say? It will solve our problem. Right?

Yes we can do that I think. Let's discuss all the problems and handle them with the best solutions! Also, I ave posted some solutions for export options in #17 , where we have to do some operations on the collected data. So we can probably club these error handlings and those together to maximize the speed of processing. What do you think?

**Comment by IshaGupta18** [comment]
Also, we can actually think of a proper update button. For that, we'll have to properly think of the UI part.

**Comment by namangupta01** [comment]
I think we can leave the exporting option for now and do later in the project.

**Comment by IshaGupta18** [comment]
Yeah sure! Would like to handle these cases by merging this and pulling the code?

**Comment by namangupta01** [comment]
For now, we are not focuing on ui. Just simple button for updating graph?

**Comment by IshaGupta18** [comment]
Sure, we can do that too

**Comment by IshaGupta18** [comment]
Although, that might not be very important for now, but it can be implemented!

**Comment by namangupta01** [comment]
And one suggestion, when you merge any pr, merge it using `squash and merge`. It will make one commit in the main branch.

**Comment by IshaGupta18** [comment]
Okay thanks for the tip!

**Comment by IshaGupta18** [comment]
@jywarren what do you think about this?

**Comment by IshaGupta18** [comment]
Okay so I have handled the issue of showing the checkboxes against the valid columns only:
image

Is this good to go @namangupta01 ? Also, I have displayed the whole table but the checkboxes are against only the valid columns. Do you think I should show only the valid columns and the checkboxes, which would reduce the size of the 2nd table since, in the first table, all columns are bring shown anyways? What do you think/

**Comment by IshaGupta18** [comment]
I would also request @SidharthBansal @gauravano @Souravirus to have a look at the progress for the project in this repo! Thanks a lot!

**Comment by IshaGupta18** [comment]
Okay! So here is one more feature: Graphing menu with different graph types:
@jywarren @namangupta01 kindly give your views on it! Thanks a lot!


menu2

**Comment by SidharthBansal** [comment]
Graphing menus are superb. Can we have colours introduced in it instead of grey colour always?
Superb Isha

**Comment by IshaGupta18** [comment]
Thank you so much! Absolutely, this is just the functional model, the
entire designing of the UI and the graphs has to be tackled!

**Comment by jywarren** [comment]
I think this is looking great. I think there's a Bootstrap "table" style
that gives some nice table padding, if you want to try that? This is so
exciting, Isha and Naman!

**Comment by IshaGupta18** [comment]
Thanks a lot! We will be designing the UI as per the designed proposed in my proposal. I hope the working is okay so that I can proceed with the design!

**Comment by IshaGupta18** [comment]
Okay so the color scheme has been designed!
image

**Comment by IshaGupta18** [comment]
@jywarren @namangupta01 what do you think of this?

**Comment by IshaGupta18** [comment]
And also I am working on the UI for this file now, so I think it would be better if we can merge this pretty big PR now. What do you say?

**Comment by jywarren** [comment]
oh wow. If Naman is cool with it then go ahead and merge!

**Comment by namangupta01** [comment]
Nice work @IshaGupta18! Looks good to me. Let get this merge!

**Comment by SidharthBansal** [comment]
Awesome folks

**Pull request merged**
