### PR TITLE
Sample data generation and table display

### LINKED ISSUE #16: Collection of sample data and table display
@jywarren @namangupta01 #15 is the PR for this issue, kindly have a look at it's functioning. Thanks a ton!

### PR DESCRIPTION
**Pull request by IshaGupta18**
fixes #16 
Okay so I have written the functions for extracting the sample data and generating the tables for selection of x-axis column and y-axis columns dynamically.

sample

Next step will be to compile the selected columns and send it to chart.js for plotting.

Let me know how this looks @jywarren @namangupta01

### CODE REVIEW

**Comment by namangupta01** [comment]
Have opened an issue #14, have a look at it.

**Comment by namangupta01** [comment]
This looks good.

**Comment by namangupta01** [comment]
Why not x-axis can have multiple selections?

**Comment by IshaGupta18** [comment]
Because on the x-axis we have a single set of labels right? And on the y
axis we can have multiple columns corresponding to those labels. Like days
on the x axis and say temperatures for each day on y. Graphs are mostly of
these types as far as I have seen. What do you think?

**Comment by namangupta01** [comment]
What about this type of graph?
Screen Shot 2019-05-09 at 8 18 18 PM

**Comment by namangupta01** [comment]
But I think this will be more complex to do. And also this will consider another axis.

**Comment by namangupta01** [comment]
Because we are not introducing any z-axis as of now.

**Comment by IshaGupta18** [comment]
Yes it looks more like a 3 D graph right?

**Comment by IshaGupta18** [comment]
yes, because the kind of data we may have to plot just involve the 2 axes only.

**Comment by namangupta01** [comment]
So you are now working on this..so I have started working on selected columns and send it to chart.js for plotting part

**Comment by namangupta01** [comment]
yes, right!

**Comment by IshaGupta18** [comment]
so let me just give you the collected data in a has kind of form, or will you do that? I can explain you the code a little to help you compile this data to a form that can be easily given to chart.js.

**Comment by IshaGupta18** [comment]
Also, I can also help you with the chart.js part because I will also like to explore that library a little. We can work on it together, like you can pass the data and I can work on the design part and graph selection

**Comment by namangupta01** [comment]
I think I can look, If I needing some help I will let you know. I will also be making modules and dividing the parsing.js into multiple modules.

**Comment by IshaGupta18** [comment]
Okay, no problem. Let me know once you have passed the data to chart.js, I'll start with remaining work for chart.js

**Comment by namangupta01** [comment]
Pass the data? Isn't is it somewhat already done here. Because you are printing the data in the console so I think the passing of data part is done? No?

**Comment by namangupta01** [comment]
We already have the data ? Right?

**Comment by IshaGupta18** [comment]
We have the data but not in the compiled form for chart.js. You'll have to make it in a hash like format and give it to chart.js. See here:
image
image

**Comment by namangupta01** [comment]
Okay! I have a doubt in mind. Maybe @jywarren can show some light on it. We can use multiple charts on a single page, right?

**Comment by IshaGupta18** [comment]
Yes I have written all about it in my proposal! We can discuss over it once
you finish the basic plotting!

**Comment by namangupta01** [comment]
I looked at it. Its multiple charts from the same CSV file. But I was talking about charts from different csv sheets. Because as of now we are making the system very rigid, or not scalable -- multiple graphs from multiple CSV files, and we are making changes in the `update_file.html` file where we should not do this we should only use this for testing. Library should be such that after including only one script in any of the projects we should call a simple function and all this stuff should happen itself -- this is what happens in the standard libraries as far as I know. User can do additional styling if he wants to do but that is not necessary, all the default styling should come only by calling a function. And also we should divide our code in different module in order to make code modularity.
Let me know your views @jywarren and @IshaGupta18.

**Comment by jywarren** [comment]
OK, I'm not sure if I'm following exactly, but one way to approach
customization vs. simplicity is to have /very/ strong defaults, which is to
say, thinking of a system which can accommodate flexibility and different
options, but /by default/ uses a simple input and simple output. I think
that's a useful design pattern that could help here, perhaps?

**Comment by namangupta01** [comment]
Yes, by default simple input and simple output. Just like other libraries, for example: Chart.js, which provides default output when we pass no additional parameters in functional calling but we have an option to do. It would be better to discuss before, what type of approach and system we want in future.

**Comment by IshaGupta18** [comment]
Yes it will be a good idea in the future, but we'll have to look for efficient ways to implement it, because the implementation might not be very easy. Right now, my approach is to make the system as flexible as it can be, for this point of time. About integration with plots2, we should look at how the Editor has been integrated, because it works very well and is neat. So, yes, we'll have to discuss it at length, on the best way to do this

**Comment by namangupta01** [comment]
One minor doubt, related to this. Asked in https://github.com/publiclab/simple-data-grapher/pull/18#issuecomment-491351668

**Comment by namangupta01** [comment]
Closing this because already processing with this in #18

**Pull request closed without merging**
