### PR TITLE
Add graph feature

### PR DESCRIPTION
**Pull request by IshaGupta18**
@jywarren @namangupta01 this is the "Add Graph" feature, which however has a bug. @namangupta01 lets solve this one together! 

Here's the gif of feature and the bug!
addgraph2

### CODE REVIEW

**Comment by IshaGupta18** [comment]
@jywarren @namangupta01 why do you think the graphs conflict? Is it something because of the hover actions?

**Comment by IshaGupta18** [comment]
@gauravano could you have a look here as well?

**Comment by IgorWilbert** [comment]
@IshaGupta18 I saw you included the settings to make this graph in the gif too. Does this bug appear if you use different settings, say `y-axis` instead of `x-axis` ? Since I think it should not have any animation and your `css` looks alright, your problem is probably related to JavaScript, maybe the `colorGenerator` or `scales` functions

**Comment by IshaGupta18** [comment]
I am so sorry, I resolved this bug and merged it with the latest code, so I was supposed to close this PR, really sorry to have caused confusion.

**Pull request closed without merging**
