### PR TITLE
Remove console log statements

### LINKED ISSUE #97: Remove unnecessary console.log statements
Please Note:  **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

**Problem**
There are a lot of unnecessary `console.log` statements defined inside all the javascript functions
 in `src` folder.

**Expected behavior**

We should remove all of those console statements 

**Link to file**

You can find all the files https://github.com/publiclab/simple-data-grapher/tree/main/src

### PR DESCRIPTION
**Pull request by chiragbhansali**
Fixes #97 

Removed the `console.log` statements in [this folder](https://github.com/publiclab/simple-data-grapher/tree/main/src)

@debck Please tell if this is fine.

### CODE REVIEW

**Comment by debck** [comment]
@SidharthBansal  I think this is ready for merging. Can you check it once

**Comment by chiragbhansali** [comment]
@debck Thanks! Can you please approve the task on the GCI dashboard?

**Comment by debck** [comment]
Yes sure. But I want Sidharth to first merge it here and then I will approve it.

**Comment by keshav234156** [comment]
@IshaGupta18

**Comment by IshaGupta18** [comment]
Excellent linting work here @chiragbhansali! Thanks a lot!

**Pull request merged**
